Lab/2 python
nikitosoleil/metaprog pull request #3
Opened 2020-11-15 21:52 UTC by nikitosoleil

2020-11-16 20:42 UTC, hoherchak requested changes
Розгляньте також випадок, коли докстрінг є, але він неповний/некоректний. При цьому якщо він коректний, то його не замінюємо. Також відсутні docstring для класів.
Опрацюйте перевірку та редагування імен файлів, каталогів (мають бути snake_case).
Зверніть увагу на помилки обробки бібліотеки https://github.com/python/typeshed.

2020-11-22 22:18 UTC, hoherchak requested changes
Оновіть на PyPi

2020-11-22 22:46 UTC, hoherchak requested changes
Все ще помилки в typeshed:
```
def parse_input_file(input_file: str) -> Dict[str, Set[str]]:
    to_remove = defaultdict(set)
    with open(input_file) as f:
        for filename, wl_entry in [parse_input_line(li) for li in f if li.strip()]:
            to_remove[filename].add(wl_entry)
    return to_remove
```
Перейменування файлів/каталогів все ще не бачу.
Поки на 9. Виправляйте помилки (якщо звісно претендуєте на більше). Захист найближчої пари, запрошення в календарі.

2020-11-22 23:10 UTC, nikitosoleil commented
Перейменування файлів/каталогів відбувається у режимі -p (Verifies and converts file and directory names **in project** to snake_case) без видалення файлів/каталогів з некоректними назвами (зручно з використанням --output-prefix)

2020-11-23 08:35 UTC, hoherchak requested changes
Не писав би якби для мене працювало. Бачу помилку в логах, але жодних виправлень, тобто створень каталогу з правильною назвою я не бачу. Каталоги і файли мають перейменовуватися на місці.
Поки на 10.

2020-11-24 19:38 UTC, hoherchak approved these changes

2020-12-06 18:52 UTC, merged